# Generated by Django 4.2.1 on 2024-11-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['-time_create'], name='testik_test_time_cr_1f8d9a_idx'),
        ),
    ]
