# Generated by Django 4.2.1 on 2024-11-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0002_alter_test_options_test_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
