# Generated by Django 4.2.1 on 2024-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0003_alter_test_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
