# Generated by Django 4.2.1 on 2024-11-24 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0005_category_test_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testik.category'),
        ),
    ]
